-   id: gray
    name: gray
    description: 'Gray: The alternative Python code formatter to Black'
    entry: gray
    language: python
    language_version: python3
    require_serial: true
    types: [python]
