dist: xenial
language: python
cache: pip
env:
- TEST_CMD="coverage run tests/test_gray.py"
install:
- pip install coverage coveralls flake8 flake8-bugbear mypy
- pip install -e '.[d]'
script:
- $TEST_CMD
after_success:
- coveralls
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
    - name: "mypy"
      python: 3.6
      env:
        - TEST_CMD="mypy gray.py grayd.py tests/test_gray.py"
    - name: "gray"
      python: 3.7
      env:
        - TEST_CMD="gray --check --verbose ."
    - name: "flake8"
      python: 3.7
      env:
        - TEST_CMD="flake8 gray.py grayd.py tests/test_gray.py"
    - name: "3.6"
      python: 3.6
    - name: "3.7"
      python: 3.7
    - name: "3.8-dev"
      python: 3.8-dev
before_deploy:
  - pip install pyinstaller
  - pyinstaller --clean -F --add-data blib2to3/:blib2to3 gray.py
